// app-veterinaria/src/app/components/carouselbanner/carouselbanner.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Router } from '@angular/router'; // Agrega esto

interface SlideData {
  id: number;
  image: string;
  alt: string;
  theme: 'veterinaria' | 'ecommerce' | 'adopcion';
  title: string;
  description: string;
  buttonText: string;
}

@Component({
  selector: 'app-carouselbanner',
  templateUrl: './carouselbanner.component.html',
  styleUrls: ['./carouselbanner.component.scss'],
  standalone: false,
})
export class CarouselbannerComponent implements OnInit, OnDestroy {
  
  activeIndex: number = 0;
  isTransitioning: boolean = false;
  isHovered: boolean = false;
  private autoSlideInterval: any;
  
   slides: SlideData[] = [
    {
      id: 0,
      image: 'assets/images/veterinaria.jpg',
      alt: 'Servicios Veterinarios',
      theme: 'veterinaria',
      title: 'Cuidamos a quien más quieres',
      description: 'Atención médica veterinaria de calidad con un equipo profesional',
      buttonText: 'Ver servicios veterinarios'
    },
    {
      id: 1,
      image: 'assets/images/ecommerce.jpg',
      alt: 'Tienda Online',
      theme: 'ecommerce',
      title: 'Todo para tu mascota en un solo lugar',
      description: 'Productos de calidad con entrega rápida a domicilio',
      buttonText: 'Visitar nuestra tienda'
    },
    {
      id: 2,
      image: 'assets/images/adopcion.jpg',
      alt: 'Adopciones',
      theme: 'adopcion',
      title: 'Adopta una vida, cambia dos destinos',
      description: 'En Happy Pet trabajamos para dar un nuevo hogar a mascotas rescatadas',
      buttonText: 'Conoce nuestros peludos'
    }
  ];

  constructor(private router: Router) {} 

  ngOnInit() {
    this.startAutoSlide();
  }

  ngOnDestroy() {
    this.stopAutoSlide();
  }

  handleSlideChange(selectedIndex: number) {
    if (selectedIndex === this.activeIndex) return;
    
    this.isTransitioning = true;
    this.activeIndex = selectedIndex;
    
    setTimeout(() => {
      this.isTransitioning = false;
    }, 600);
  }

  goToPrevious() {
    const prevIndex = (this.activeIndex - 1 + this.slides.length) % this.slides.length;
    this.handleSlideChange(prevIndex);
  }

  goToNext() {
    const nextIndex = (this.activeIndex + 1) % this.slides.length;
    this.handleSlideChange(nextIndex);
  }

  onMouseEnter() {
    this.isHovered = true;
    this.stopAutoSlide();
  }

  onMouseLeave() {
    this.isHovered = false;
    this.startAutoSlide();
  }

  onMainActionClick() { 
    const currentSlide = this.slides[this.activeIndex];
    
    switch (currentSlide.theme) {
      case 'veterinaria':
        // Navegar a servicios veterinarios
        this.router.navigate(['/especialidadespage']); 
        break;
      case 'ecommerce':
        this.router.navigate(['/shop']);
        break;
      case 'adopcion':
        break;
    }
  }

  getCurrentSlide(): SlideData {
    return this.slides[this.activeIndex];
  }

  getSlideThemeClass(): string {
    return `${this.getCurrentSlide().theme}Message`;
  }

  getCarouselClasses(): string {
    let classes = 'carousel-wrapper';
    if (this.isTransitioning) {
      classes += ' transitioning';
    }
    return classes;
  }

  private startAutoSlide() {
    this.stopAutoSlide();
    this.autoSlideInterval = setInterval(() => {
      if (!this.isHovered) {
        this.goToNext();
      }
    }, 7000);
  }

  private stopAutoSlide() {
    if (this.autoSlideInterval) {
      clearInterval(this.autoSlideInterval);
      this.autoSlideInterval = null;
    }
  }
}
<div 
  [class]="getCarouselClasses()"
  (mouseenter)="onMouseEnter()"
  (mouseleave)="onMouseLeave()">

  <!-- Carousel Container -->
  <div class="carousel">
    <!-- Slides -->
    <div class="slides-container">
      <div 
        *ngFor="let slide of slides; let i = index"
        class="slide-item"
        [class.active]="i === activeIndex"
        [class.transitioning]="isTransitioning && i === activeIndex">

        <div class="image-container">
          <img 
            [src]="slide.image"
            [alt]="slide.alt"
            class="slide-image">
        </div>
      </div>
    </div>

    <!-- Custom Controls -->
    <div class="custom-controls">
      <button 
        class="control-prev"
        (click)="goToPrevious()"
        type="button">
        <span>‹</span>
      </button>
      <button  
        class="control-next"
        (click)="goToNext()"
        type="button">
        <span>›</span>
      </button>
    </div>

    <!-- Custom Indicators -->
    <div class="custom-indicators">
      <button
        *ngFor="let slide of slides; let i = index"
        class="indicator"
        [class.active]="i === activeIndex"
        (click)="handleSlideChange(i)"
        type="button">
      </button>
    </div>

    <!-- Main Message Overlay -->
    <div class="main-message-overlay">
      <div 
        class="main-message-content"
        [ngClass]="getSlideThemeClass()">
        <h1>{{ getCurrentSlide().title }}</h1>
        <p>{{ getCurrentSlide().description }}</p>
        <button 
          class="main-action-button"
          (click)="onMainActionClick()"
          type="button">
          {{ getCurrentSlide().buttonText }}
        </button>
      </div>
    </div>
  </div>
</div>

// WEB/src/components/common/CarouselBanner/CarouselBanner.tsx
import { Carousel } from "react-bootstrap";
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom"; // Agrega esta línea
import "bootstrap/dist/css/bootstrap.min.css";
import styles from "./CarouselBanner.module.css";

const CarouselBanner = () => {
  const [isTransitioning, setIsTransitioning] = useState(false);
  const [activeIndex, setActiveIndex] = useState(0);
  const [isHovered, setIsHovered] = useState(false);
  const navigate = useNavigate(); // Asegúrate de tener esto
  
  const totalSlides = 3;
  
  const handleSlideChange = (selectedIndex: number) => {
    setIsTransitioning(true);
    setActiveIndex(selectedIndex);
    setTimeout(() => setIsTransitioning(false), 600);
  };
  
  // Efecto de animación para los indicadores personalizados
  useEffect(() => {
    const interval = !isHovered ? 
      setInterval(() => {
        const nextIndex = (activeIndex + 1) % totalSlides;
        setActiveIndex(nextIndex);
      }, 7000) : null;
    
    return () => {
      if (interval) clearInterval(interval);
    };
  }, [activeIndex, isHovered]);

  return (
    <div 
      className={`${styles.carouselWrapper} ${isTransitioning ? styles.transitioning : ''}`}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <Carousel
        fade
        id="bannerPrincipal"
        className={styles.carousel}
        indicators={false}
        activeIndex={activeIndex}
        onSelect={handleSlideChange}
        controls={false}
      >
        {/* Slide 1: Veterinaria */}
        <Carousel.Item>
          <div className={styles.imageContainer}>
            <img
              className="d-block w-100"
              src="/src/assets/images/veterinaria.jpg"
              alt="Servicios Veterinarios"
            />
          </div>
        </Carousel.Item>
        
        {/* Slide 2: Ecommerce */}
        <Carousel.Item>
          <div className={styles.imageContainer}>
            <img
              className="d-block w-100"
              src="/src/assets/images/ecommerce.jpg"
              alt="Tienda Online"
            />
          </div>
        </Carousel.Item>
        
        {/* Slide 3: Adopciones */}
        <Carousel.Item>
          <div className={styles.imageContainer}>
            <img
              className="d-block w-100"
              src="/src/assets/images/adopcion.jpg"
              alt="Adopciones"
            />
          </div>
        </Carousel.Item>
      </Carousel>
      
      {/* Control arrows personalizados */}
      <div className={styles.customControls}>
        <button 
          className={styles.controlPrev} 
          onClick={() => handleSlideChange((activeIndex - 1 + totalSlides) % totalSlides)}
        >
          <span>‹</span>
        </button>
        <button 
          className={styles.controlNext} 
          onClick={() => handleSlideChange((activeIndex + 1) % totalSlides)}
        >
          <span>›</span>
        </button>
      </div>
      
      {/* Indicadores personalizados */}
      <div className={styles.customIndicators}>
        {[...Array(totalSlides)].map((_, index) => (
          <button
            key={index}
            className={`${styles.indicator} ${activeIndex === index ? styles.active : ''}`}
            onClick={() => handleSlideChange(index)}
          />
        ))}
      </div>
      
      {/* Mensaje principal basado en el slide activo */}
      <div className={styles.mainMessageOverlay}>
        {activeIndex === 0 && (
          <div className={`${styles.mainMessageContent} ${styles.veterinariaMessage}`}>
            <h1>Cuidamos a quien más quieres</h1>
            <p>Atención médica veterinaria de calidad con un equipo profesional</p>
            <button
              className={styles.mainActionButton}
              onClick={() => navigate("/especialidadespage")}
            >
              Ver servicios veterinarios
            </button>
          </div>
        )}
        
        {activeIndex === 1 && (
          <div className={`${styles.mainMessageContent} ${styles.ecommerceMessage}`}>
            <h1>Todo para tu mascota en un solo lugar</h1>
            <p>Productos de calidad con entrega rápida a domicilio</p>
            <button
              className={styles.mainActionButton}
              onClick={() => navigate("/shop")}
            >
              Visitar nuestra tienda
            </button>
          </div>
        )}
        
        {activeIndex === 2 && (
          <div className={`${styles.mainMessageContent} ${styles.adopcionMessage}`}>
            <h1>Adopta una vida, cambia dos destinos</h1>
            <p>En Happy Pet trabajamos para dar un nuevo hogar a mascotas rescatadas</p>
            <button className={styles.mainActionButton}>
              Conoce nuestros peludos
            </button>
          </div>
        )}
      </div>
    </div>
  );
};

export default CarouselBanner;
