// app-veterinaria/src/app/components/header/header.component.ts
import { Component, HostListener } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../service/auth.service'; 

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.scss'],
  standalone: false 
})
export class HeaderComponent {
  mobileMenuOpen = false;
  scrolled = false;
  showModal = false;
  isLoggedIn = false;

  constructor(private router: Router, private authService: AuthService) {
    this.checkAuthStatus();
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.scrolled = window.scrollY > 50;
  }

  checkAuthStatus() {
    this.isLoggedIn = !!localStorage.getItem('token');
  }

  toggleMenu() {
    this.mobileMenuOpen = !this.mobileMenuOpen;
    document.body.style.overflow = this.mobileMenuOpen ? 'hidden' : 'unset';
  }

  // Cierra el menú después de un pequeño delay para asegurar la navegación
  closeMenuAfterDelay() {
    setTimeout(() => {
      this.mobileMenuOpen = false;
      document.body.style.overflow = 'unset';
    }, 150);
  }

  showLogoutModal() {
    this.showModal = true;
    this.mobileMenuOpen = false;
  }

  confirmLogout() { 
    this.authService.logout(); 
    localStorage.removeItem('token');
    localStorage.removeItem('currentUserRut');
    this.showModal = false;
    this.isLoggedIn = false;
    this.router.navigate(['/login']); 
  }

  closeModal() {
    this.showModal = false;
  }
}
<header [class.header]="true" [class.scrolled]="scrolled">
  <nav class="container">
    <div class="nav-wrapper">
      <!-- Logo y marca -->
      <a class="brand" routerLink="/" (click)="closeMenuAfterDelay()">
        <ion-icon name="paw" class="l ogo"></ion-icon>
        <span>Happy Pet</span>
      </a>

      <!-- Botón hamburguesa -->
      <button
        class="hamburger"
        [class.hamburgerOpen]="mobileMenuOpen"
        aria-label="Abrir menú"
        [attr.aria-expanded]="mobileMenuOpen"
        (click)="toggleMenu()"
      >
        <ion-icon name="paw" class="logo"></ion-icon>
      </button>

      <!-- Menú de navegación -->
      <div class="nav-menu" [class.show-menu]="mobileMenuOpen">
        <ul class="nav-list">
          <!-- Opciones para usuario logueado -->
          <ng-container *ngIf="isLoggedIn">
            <li class="nav-item">
              <a class="nav-link" routerLink="/" (click)="closeMenuAfterDelay()">
                <ion-icon name="home" class="nav-icon"></ion-icon>
                <span>Inicio</span>
              </a>
            <li class="nav-item">
              <a class="nav-link" routerLink="/citas" (click)="closeMenuAfterDelay()">
                <ion-icon name="calendar" class="nav-icon"></ion-icon>
                <span>Mis Citas</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" routerLink="/userprofile" (click)="closeMenuAfterDelay()">
                <ion-icon name="person-circle" class="nav-icon"></ion-icon>
                <span>Perfil</span>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" routerLink="/pets" (click)="closeMenuAfterDelay()">
                <ion-icon name="paw" class="nav-icon"></ion-icon>
                <span>Mis Mascotas</span>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" routerLink="/agendamiento-citas" (click)="closeMenuAfterDelay()">
                <ion-icon name="calendar" class="nav-icon"></ion-icon>
                <span>Agendamiento de Citas</span>
              </a>
            </li>


            <li class="nav-item">
              <button class="logout-button" (click)="showLogoutModal()">
                <ion-icon name="log-out" class="nav-icon"></ion-icon>
                <span>Cerrar Sesión</span>
              </button>
            </li>
          </ng-container>

          <!-- Opciones para usuario no logueado -->
          <ng-container *ngIf="!isLoggedIn">
            <li class="nav-item">
              <a class="nav-link" routerLink="/login" (click)="closeMenuAfterDelay()">
                <ion-icon name="log-in" class="nav-icon"></ion-icon>
                <span>Iniciar Sesión</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" routerLink="/register" (click)="closeMenuAfterDelay()">
                <ion-icon name="person-add" class="nav-icon"></ion-icon>
                <span>Registrarse</span>
              </a>
            </li>
          </ng-container>
        </ul>
      </div> 
    </div>
  </nav>

  <!-- Modal de confirmación de logout (solo para usuarios logueados) -->
  <div *ngIf="showModal && isLoggedIn" class="modalOverlay" (click)="closeModal()">
    <div class="modal" (click)="$event.stopPropagation()">
      <div class="modalIcon">
        <ion-icon name="log-out"></ion-icon>
      </div>
      
      <h3>Confirmar Cierre de Sesión</h3>
      <p>¿Estás seguro de que quieres cerrar sesión?</p>
      
      <div class="modalButtons">
        <button (click)="confirmLogout()" class="confirmButton">
          Sí, cerrar sesión
        </button>
        <button (click)="closeModal()" class="cancelButton">
          Cancelar
        </button>
      </div>
    </div>
  </div>
</header>

// WEB/src/components/common/Header/Header.tsx
import { useState, useEffect } from "react";
import { NavLink, useNavigate, useLocation } from "react-router-dom";
import { FaPaw, FaUserCircle, FaHome, FaSignInAlt, FaUserPlus, FaSignOutAlt, FaTimes, FaCalendarAlt } from "react-icons/fa";
import { useAuth } from "../../../utils/AuthContext";
import styles from "./header.module.css";

const Header = () => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [showLogoutConfirm, setShowLogoutConfirm] = useState(false);
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const { isLoggedIn, logout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  useEffect(() => {
    const handleScroll = () => {
      setScrolled(window.scrollY > 50);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  useEffect(() => {
    setMobileMenuOpen(false);
  }, [location.pathname]);

  // Prevenir scroll del body cuando el menú está abierto
  useEffect(() => {
    if (mobileMenuOpen) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'unset';
    }
    
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [mobileMenuOpen]);

  const closeMenu = () => {
    if (isMenuOpen) setIsMenuOpen(false);
    setMobileMenuOpen(false);
  };

  const confirmLogout = () => {
    logout();
    setShowLogoutConfirm(false);
    closeMenu();
    navigate("/");
  };

  const handleMenuItemClick = () => {
    setMobileMenuOpen(false);
  };

  return (
    <header className={`${styles.header} ${scrolled ? styles.scrolled : ''}`}>
      <nav className={styles.container}>
        <div className={styles.navWrapper}>
          <NavLink to="/" className={styles.brand} onClick={closeMenu}>
            <FaPaw className={styles.logo} /> Happy Pet
          </NavLink>

          {/* Botón hamburguesa mejorado */}
          <button
            className={`${styles.hamburger} ${mobileMenuOpen ? styles.hamburgerOpen : ''}`}
            aria-label="Abrir menú"
            aria-expanded={mobileMenuOpen}
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
          >
            <span className={styles.hamburgerIcon}></span>
          </button>

          {/* Botón para toggle del sidebar en desktop */}
          <button
            className={styles.sidebarToggle}
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            aria-label="Alternar menú lateral"
          >
            <FaPaw className={styles.toggleIcon} />
          </button>

          {/* Overlay para cerrar el menú solo en móvil */}
          {mobileMenuOpen && window.innerWidth < 992 && (
            <div
              className={styles.menuOverlay}
              onClick={() => setMobileMenuOpen(false)}
            />
          )}

          {/* Menú lateral (sidebar) */}
          <div className={`${styles.sidebar} ${mobileMenuOpen ? styles.sidebarOpen : ''}`}>
            {/* Header del sidebar */}
            <div className={styles.sidebarHeader}>
              <div className={styles.sidebarBrand}>
                <FaPaw className={styles.sidebarLogo} />
                <span>Happy Pet</span>
              </div>
              <button
                className={styles.closeSidebar}
                onClick={() => setMobileMenuOpen(false)}
                aria-label="Cerrar menú"
              >
                <FaTimes />
              </button>
            </div>

            {/* Contenido del sidebar */}
            <div className={styles.sidebarContent}>
              <nav className={styles.sidebarNav}>
                <NavLink
                  to="/"
                  end
                  className={({ isActive }) =>
                    isActive ? `${styles.sidebarMenuItem} ${styles.sidebarMenuItemActive}` : styles.sidebarMenuItem
                  }
                  onClick={handleMenuItemClick}
                >
                  <FaHome className={styles.sidebarIcon} />
                  <span>Inicio</span>
                </NavLink>

                {!isLoggedIn ? (
                  <>
                    <NavLink
                      to="/login"
                      className={({ isActive }) =>
                        isActive ? `${styles.sidebarMenuItem} ${styles.sidebarMenuItemActive}` : styles.sidebarMenuItem
                      }
                      onClick={handleMenuItemClick}
                    >
                      <FaSignInAlt className={styles.sidebarIcon} />
                      <span>Iniciar Sesión</span>
                    </NavLink>
                    <NavLink
                      to="/register"
                      className={({ isActive }) =>
                        isActive ? `${styles.sidebarMenuItem} ${styles.sidebarMenuItemActive}` : styles.sidebarMenuItem
                      }
                      onClick={handleMenuItemClick}
                    >
                      <FaUserPlus className={styles.sidebarIcon} />
                      <span>Registro</span>
                    </NavLink>
                  </>
                ) : ( 
                  <>
                    {/* Botón "Mis Mascotas" */}
                    <NavLink
                      to="/mascotas"
                      className={({ isActive }) =>
                        isActive ? `${styles.sidebarMenuItem} ${styles.sidebarMenuItemActive}` : styles.sidebarMenuItem
                      }
                      onClick={handleMenuItemClick}
                    >
                      <FaPaw className={styles.sidebarIcon} />
                      <span>Mis Mascotas</span>
                    </NavLink>

                    {/* Botón "Agendamiento de Citas" */}
                    <NavLink
                      to="/agendamientoCitas"
                      className={({ isActive }) =>
                        isActive ? `${styles.sidebarMenuItem} ${styles.sidebarMenuItemActive}` : styles.sidebarMenuItem
                      }
                      onClick={handleMenuItemClick}
                    >
                      <FaCalendarAlt className={styles.sidebarIcon} />
                      <span>Agendamiento de Citas</span>
                    </NavLink>

                    {/* Nuevo botón "Mis Citas" */}
                    <NavLink
                      to="/citas"
                      className={({ isActive }) =>
                        isActive ? `${styles.sidebarMenuItem} ${styles.sidebarMenuItemActive}` : styles.sidebarMenuItem
                      }
                      onClick={handleMenuItemClick}
                    >
                      <FaCalendarAlt className={styles.sidebarIcon} />
                      <span>Mis Citas</span>
                    </NavLink>

                    <NavLink
                      to="/UserProfile"
                      className={({ isActive }) =>
                        isActive ? `${styles.sidebarMenuItem} ${styles.sidebarMenuItemActive}` : styles.sidebarMenuItem
                      }
                      onClick={handleMenuItemClick}
                    >
                      <FaUserCircle className={styles.sidebarIcon} />
                      <span>Mi Perfil</span>
                    </NavLink>
                    
                    <div className={styles.sidebarDivider}></div>
                    
                    <button
                      onClick={() => {
                        setShowLogoutConfirm(true);
                        setMobileMenuOpen(false);
                      }}
                      className={`${styles.sidebarMenuItem} ${styles.logoutMenuItem}`}
                    >
                      <FaSignOutAlt className={styles.sidebarIcon} />
                      <span>Cerrar Sesión</span>
                    </button>
                  </>
                )}
              </nav>
            </div>
          </div>
        </div>
      </nav>

      {/* Modal de confirmación */}
      {showLogoutConfirm && (
        <div className={styles.modalOverlay}>
          <div className={styles.modal}>
            <div className={styles.modalIcon}>
              <FaSignOutAlt />
            </div>
            <h3>Confirmar Cierre de Sesión</h3>
            <p>¿Estás seguro de que quieres cerrar sesión?</p>
            <div className={styles.modalButtons}>
              <button onClick={confirmLogout} className={styles.confirmButton}>
                Sí, cerrar sesión
              </button>
              <button onClick={() => setShowLogoutConfirm(false)} className={styles.cancelButton}>
                Cancelar
              </button>
            </div>
          </div>
        </div>
      )}
    </header>
  );
};

export default Header;
